Приклади з доп. матеріалів

In [70]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [71]:
def load_data(filename):
    data = np.loadtxt(filename, delimiter=',')
    X = data[:,:2]
    y = data[:,2]
    return X, y

In [72]:
def plot_data(X, y, pos_label="y=1", neg_label="y=0"):
    positive = y == 1
    negative = y == 0

    # plot example
    plt.plot(X[positive, 0], X[positive, 1], "k+", label=pos_label)
    plt.plot(X[negative, 0], X[negative, 1], "yo", label=neg_label)

In [73]:
# # X_train, y_train = load_data("iris.csv")

# # plot examples
# plt.figure(figsize=(10, 7))
# plot_data(X_train, y_train[:], pos_label="Addmited", neg_label="Not addmited")

# # set the y-axis label
# plt.xlabel("Exam 2 score")
# # set the x-axis label
# plt.ylabel("Exam 1 score")
# plt.legend(loc="upper right")
# plt.show()

Практика з конспекту:

In [74]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression

X, y = load_iris(return_X_y=True)
clf = LogisticRegression(random_state=0).fit(X, y)

print(clf.score(X, y))
print(clf.coef_)
print(clf.intercept_)

0.9733333333333334
[[-0.42152284  0.96482473 -2.51994006 -1.08433494]
 [ 0.52943001 -0.31458703 -0.2016019  -0.94494217]
 [-0.10790716 -0.65023769  2.72154195  2.02927711]]
[  9.86202957   2.2288098  -12.09083936]


c:\Users\yulic\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


#### One vs Rest Classifier
##### Стратегія "Один проти всіх"

In [75]:
import numpy as np
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC

# Створюємо набір даних, NumPy масив, що представляє 2D вектори ознак. 
# Кожен рядок представляє точку даних, а кожен стовпець - ознаку.  
XX = np.array([
    [10, 10],
    [8, 10],
    [-5, 5.5],
    [-5.4, 5.5],
    [-20, -20],
    [-15, -20]
])

# Створюємо NumPy масив, що представляє мітки класів
y = np.array([0, 0, 1, 1, 2, 2])

# Побудова моделі
clf = OneVsRestClassifier(SVC()).fit(XX, y)

# Прогнозування моделі. 
# Метод predict використовується для прогнозування класів нових даних.
# В цьому випадку передаються три нові зразки
clf.predict([[-19, -20], [9, 9], [-5, 5]])

# Код поверне прогнозовані класи для кожного з нових зразків. 
# Результат [2, 0, 1] означає, що перший зразок належить до класу 2, 
# другий — до класу 0, а третій — до класу 1

array([2, 0, 1])

#### One vs One Classifier
##### Стратегія "Один проти одного"

In [76]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.multiclass import OneVsOneClassifier
from sklearn.svm import LinearSVC

# Завантаження та розділення даних на навчальний та тестовий набори.
# Параметр test_size=0.33 вказує, що 33% даних буде використано для тестування, 
# а shuffle=True гарантує, що дані будуть перемішані перед розділенням. 
# random_state=0 забезпечує повторюваність результатів.
X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, shuffle=True, random_state=0)

# Побудова та навчання моделі:
clf = OneVsOneClassifier(
    LinearSVC(random_state=0)).fit(X_train, y_train)

# Прогнозування: 
# predict використовується для прогнозування класів перших 10 зразків
# з тестового набору X_test
clf.predict(X_test[:10])

# Код поверне прогнозовані класи для перших 10 зразків з тестового набору. 
# результат [2, 0, 1, 1, 2, 0, 1, 2, 1, 0] означає, що модель прогнозує класи для цих зразків відповідно.

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1])